triggers:
  - keyword: shopify_order_close

steps:
  - ask: order id?

  - type: meya.shopify.component.order.close
    order_id: (@ flow.result | int)
    integration: integration.shopify

  - say: 'result: '
  - delay: 1
  - say: (@ flow.result | string)
