triggers:
  - keyword: shopify_order_status

steps:
  - ask: customer id?

  - type: meya.shopify.component.customer.order.list
    customer_id: (@ flow.result | int)
    financial_status: any
    fulfillment_status: any
    status: any
    integration: integration.shopify

  - type: meya.shopify.component.order.display
    orders: (@ flow.result)
    integration: integration.shopify

  - ask: Select order for status
    tiles: (@ flow.result)

  - type: meya.shopify.component.order.status
    order: (@ flow.result)

  - say: order status (@ flow.result)
