triggers:
  - keyword: shopify_order_update_shipping_address

steps:
  - say: Shipping address?
  - type: text_input
    required: true
  - flow_set: address

  - say: Address 2?
  - type: text_input
    required: true
  - flow_set: address_2

  - say: City?
  - type: text_input
    required: true
  - flow_set: city

  - say: Postal code?
  - type: text_input
    required: true
  - flow_set: postal_code

  - say: Country?
  - type: text_input
    required: true
  - flow_set: country

  - say: Province?
  - type: text_input
    required: true
  - flow_set: province

  - type: meya.shopify.component.order.update_shipping_address
    order_id: (@ flow.order_id | int)
    address: (@ flow.address )
    address_2: (@ flow.address_2 )
    city: (@ flow.city )
    postal_code: (@ flow.postal_code )
    country: (@ flow.country )
    province: (@ flow.province )
    integration: integration.shopify

  - say: Shipping address updated successfully
