triggers:
  - keyword: js
  - button_id: .js

steps:
  - ask: Want to run some code?
    tiles:
      - title: pow(2, 10)
        javascript: alert(Math.pow(2, 10))
      - buttons:
          - text: Static button
            javascript: orb.click('.js')
          - text: Dynamic button
            javascript: alert('DYNAMIC BUTTON')
            result: DYNAMIC
    quick_replies:
      - text: Next
        action: next
  - say: Code ran (@ flow.get("result") )

  - buttons:
      - text: Start spin
        javascript: document.querySelector('.orb-h1').classList.add('infinite-spinning')
      - text: Stop spin
        javascript: document.querySelector('.orb-h1').classList.remove('infinite-spinning')
    quick_replies:
      - text: Next
        action: next
      - text: Say
        javascript: orb.say(prompt('Say what?'))
  - say: Code ran (@ flow.get("result") )
