triggers:
  - keyword: demo google actions ssml
steps:
  # Google SSML reference: https://cloud.google.com/text-to-speech/docs/ssml
  - say: >-
      <par>
        <media xml:id="question" begin="0.5s">
          <speak>Who invented the Internet?</speak>
        </media>
        <media xml:id="answer" begin="question.end+2.0s">
          <speak>The Internet was invented by cats.</speak>
        </media>
        <media begin="answer.end-0.2s" soundLevel="-6dB">
          <audio
            src="https://actions.google.com/sounds/v1/cartoon/cartoon_boing.ogg"/>
        </media>
        <media repeatCount="3" soundLevel="+2.28dB"
          fadeInDur="2s" fadeOutDur="0.2s">
          <audio
            src="https://actions.google.com/sounds/v1/animals/cat_purr_close.ogg"/>
        </media>
      </par>
