icon:
  bird: streamline-regular/33-pets-animals/12-wild birds/wild-bird.svg
  cat: streamline-regular/33-pets-animals/04-cats/cat-sitting.svg
  dog: streamline-regular/33-pets-animals/03-dogs/dog.svg
  hat:
    path: streamline-regular/29-clothes-footwear-accessories/03-caps/cap-3.svg
    color: "#2bcc7c"
  moon: streamline-regular/34-weather/03-weather/weather-night-clear.svg
  pdf_file: streamline-regular/07-work-office-companies/07-office-files/office-file-pdf-1.svg
  sun: streamline-regular/34-weather/03-weather/weather-sun.svg
  txt_file: streamline-regular/07-work-office-companies/07-office-files/office-file-txt-1.svg
  question: streamline-regular/01-interface essential/14-alerts/question-circle.svg
  phone: streamline-light/07-work-office-companies/03-video-meetings/meeting-smartphone-hold-1.svg
  person: streamline-light/21-messages-chat-smileys/01-messages-people/messages-people-person-bubble-oval-1.svg
  message: streamline-light/21-messages-chat-smileys/02-messages-speech-bubbles/messages-bubble-square-typing.svg
  code: streamline-regular/04-programing-apps-websites/13-coding-files/file-code-check.svg
  help: streamline-regular/21-messages-chat-smileys/02-messages-speech-bubbles/messages-bubble-question.svg
  pie: streamline-bold/01-interface-essential/02-dashboard/pie-line-graph-desktop.svg
