triggers:
  - keyword: build_composer
  - keyword: build_default_composer
    action:
      jump: build

steps:
  - (focus)
  - ask: Focus?
    buttons:
      - text: ⏭ (skip)
        action: next
      - text: 🙊 (none)
        data:
          focus:
      - text: file
        data:
          focus: file
      - text: image
        data:
          focus: image
      - text: text
        data:
          focus: text
      - text: blur
        data:
          focus: blur

  - (placeholder)
  - ask: Placeholder?
    buttons:
      - text: ⏭ (skip)
        action: next
      - text: 🙊 (none)
        data:
          placeholder:
      - text: Something
        data:
          placeholder: Something

  - (visibility)
  - ask: Visibility?
    buttons:
      - text: ⏭ (skip)
        action: next
      - text: 🙊 (none)
        data:
          visibility:
      - text: collapse
        data:
          visibility: collapse
      - text: hide
        data:
          visibility: hide
      - text: show
        data:
          visibility: show

  - (build)
  - component.event.build_composer
  - flow_set: composer
  - ask: Configured (@ flow.composer )
    buttons:
      - text: say
        action:
          say: Composer hi
          composer: (@ flow.composer )
      - text: ask
        action:
          ask: Composer hello?
          composer: (@ flow.composer )
      - text: ask_buttons
        action:
          ask: Composer
          buttons:
            - text: a
              action: next
            - text: b
              action: next
          composer: (@ flow.composer )
      - text: ask_tiles
        action:
          ask: Composer
          tiles:
            - buttons:
                - text: a
                  action: next
            - buttons:
                - text: b
                  action: next
          composer: (@ flow.composer )
      - text: email_address_input
        action:
          type: email_address_input
          required: true
          composer: (@ flow.composer )
      - text: ask_text
        action:
          type: text_input
          composer: (@ flow.composer )
      - text: ask_file
        action:
          ask: Composer
          expect: file
          composer: (@ flow.composer )
      - text: ask_image
        action:
          ask: Composer
          expect: image
          composer: (@ flow.composer )
