triggers:
  - keyword: front_create_conversation_deprecated
    action:
      data:
        contact_source: custom

steps:
  - ask: Contact_id?
    quick_replies:
      - text: skip
        action:
          jump: ask_contact_handle
  - flow_set: contact_id
  - jump: ask_thread_ref

  - (ask_contact_handle)
  - ask: Contact handle?
    quick_replies:
      - text: skip
        action:
          jump: ask_thread_ref
  - flow_set: contact_handle

  - ask: Contact source?
    buttons:
      - text: custom
        result: custom
      - text: smooch
        result: smooch
      - text: email address
        result: email
      - text: phone
        result: phone
      - text: twitter
        result: twitter
      - text: facebook
        result: facebook
      - text: intercom
        result: intercom
    quick_replies:
      - text: skip
        action:
          jump: ask_thread_ref
  - flow_set: contact_source


  - (ask_thread_ref)
  - ask: External thread ref?
    quick_replies:
      - text: skip
        action:
          jump: ask_link_thread
  - flow_set: thread_ref

  - (ask_link_thread)
  - ask: Link thread?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: link

  - ask: Send transcript?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: send_transcript

  # This component is being deprecated
  - type: meya.front.component.conversation.create
    attachments_url:
      - https://images.unsplash.com/photo-1517352551702-336dda93455e?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1000
    link: (@ flow.link )
    assignee_email: (@ vault.front.assignee_email )
    tag_ids: (@ vault.front.tag_ids )
    inbox_id: (@ vault.front.inbox_id )
    status: archived
    thread_ref: (@ flow.get('thread_ref') )
    contact_id: (@ flow.get('contact_id') )
    contact_handle: (@ flow.get('contact_handle') )
    contact_source: (@ flow.get('contact_source') )
    send_transcript: (@ flow.send_transcript )
    integration: integration.front

  - thread_set:
      conversation_id: (@ flow.result.conversation_id )

  - say: Front conversation created. (@ flow.result | string )
