triggers:
  - lifecycle_id: start
  - keyword: sunco_start_bypass

steps:
  - if: (@ flow.event.data.context.get("source") )
    then: next
    else:
      jump: welcome
  - say: I see you are using the `(@ flow.event.data.context.source.type )` client.
  - (welcome)
  - say: Welcome to the conversation! 👋
  - typing: on
  - delay: 2
  - ask: What's your favorite color?
    quick_replies:
      - Red
      - Blue
  - say: What a coincidence! (@ flow.result ) is my favorite color, too. 😃
