triggers:
  - regex: >
      \b
      cat
      \b
    ignorecase: true

steps:
  - say: Here's a cat image
  - image: >-
      https://cataas.com/cat/gif?unique=(@
        flow.event.data.text | urlencode
      )
    alt: Random cat GIF
