triggers:
  - regex: ^mode.(.+)$
    when: (@ event_user.type.user )

steps:
  - flow_set:
      mode: (@ flow.groups[0] )
  - say: Setting mode to (@ flow.mode )...
  - mode: (@ flow.mode )
  - say: Done. To reset type "mode_bot"
