triggers:
  - keyword: zendesk_support_ticket_create
    when: true
  - keyword: zendesk_support_ticket_create_shortcut
    when: true
    action:
      jump: create
      data:
        link_user: true
        link_ticket: true
        subject:
        comment:
        name:
        email:
        phone:
  - keyword: zendesk_support_ticket_create_simple
    when: true
    action:
      jump: create_ticket_simple

steps:
  - ask: Link user?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: link_user
  - if: (@ flow.link_user )
    then:
      jump: link_ticket
    else:
      next:
  - flow_set:
      link_ticket: false
  - jump: name

  - (link_ticket)
  - ask: Link ticket?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: link_ticket

  - (name)

  # Start "prechat" mode to collect sensitive details, all user responses will be encrypted
  - thread_set:
      mode: prechat

  - say: Name?
  - type: text_input
    required: true
    label: Name
    icon: (@ config.icon.person )
    quick_replies:
      - text: Skip (generate)
        result:
  - flow_set: name

  - say: Email?
  - type: email_address_input
    required: true
    quick_replies:
      - text: Skip (blank)
        result:
  - flow_set: email

  - say: Phone?
  - type: text_input
    required: true
    label: Phone
    icon: (@ config.icon.phone )
    quick_replies:
      - text: Skip (blank)
        result:
  - flow_set: phone

  - say: Subject?
  - type: text_input
    required: true
    label: Ticket subject
    quick_replies:
      - text: Skip (generate)
        result:
  - flow_set: subject

  - say: Comment?
  - type: text_input
    required: true
    label: Ticket comment
    quick_replies:
      - text: Skip (use transcript)
        result:
  - flow_set: comment

  # Done "prechat" mode
  - thread_set:
      mode:

  - (create)
  - note: This is a note before ticket creation
  - say: Creating or updating user...
  - type: meya.zendesk.support.component.user.create_or_update
    integration: integration.zendesk.support
    link: (@ flow.link_user )
    name: (@ flow.name )
    email: (@ flow.email )
    phone: (@ flow.phone )
  - say: User (@ flow.result.id ) created or updated
  - say: Creating ticket...
  - type: meya.zendesk.support.component.ticket.create
    integration: integration.zendesk.support
    link: (@ flow.link_ticket )
    requester_id: (@ flow.result.id )
    subject: (@ flow.subject )
    comment: (@ flow.comment )
    ticket_form_id: (@ vault.zendesk.support.ticket_form_id )
    brand_id: (@ vault.zendesk.support.brand_id )
  - say: Ticket (@ flow.result.id ) created
  - note: This is a note after ticket creation
  - end

  - (create_ticket_simple)
  - note: This is a note before ticket creation
  - say: Creating ticket (automatic linked user)...
  - type: meya.zendesk.support.component.ticket.create
    integration: integration.zendesk.support
  - say: Ticket (@ flow.result.id ) created
  - note: This is a note after ticket creation
  - end
