triggers:
  - keyword: chat

steps:
  - ask: Change chat state
    buttons:
      - text: Open
        action: next
      - text: Close
        action:
          jump: close

  - (open)
  - open_chat
  - flow: flow.session.chat
    transfer: true

  - (close)
  - close_chat
  - flow: flow.session.chat
    transfer: true

