triggers:
  - type: page_open
    magic_link_error: false
    when: (@ not thread.page_open )
    action:
      data:
        page: snow capped mountains

  - type: page_open
    magic_link_error: true
    action:
      jump: magic_link_error

steps:
  - (welcome)
  - thread_set:
      page_open: (@ flow.event.data )
# uncomment if you want to track in freshchat
#  - type: meya.component.csp_track
#    integration: integration.freshchat
#    data:
#      assign_to_agent: roeland+assistant@meya.ai
#      assign_to_group: Bot
  - component.session.track
  - hero: Start your journey...
    description: Welcome to the (@ flow.page )! üîÆ
    quick_replies:
      - button
      - email
      - text: «ù…Ø…êu
        action:
          flow: flow.text.ask_name
      - text: hello
        action:
          say: hello back
      - chat
      - text: next
        action: next
      - text: typing
        action:
          flow: flow.typing_indicator.typing_indicator_initial
  - say: After hero
  - end

  - (magic_link_error)
  - flow_set:
      page_open_event: (@ flow.event )
  - ask: The magic link you clicked has expired
    buttons:
      - text: OK
        action:
          jump: welcome
          data:
            event: (@ flow.page_open_event)
            page: deep jungle
