triggers:
  - agent_command: zendesk_support_verify_phone
    action:
      jump: verify_phone

  - agent_command: zendesk_support_get_price\s(?P<product>\S+)
    action:
      jump: get_price

steps:
  - (verify_phone)
  # Publish as the agent
  - flow_set:
      event_user_id: (@ flow.event.data.user_id )
  - ask: OK, to verify, what is your phone number?
  - flow_set: phone
  - type: meya.zendesk.support.component.user.show
    integration: integration.zendesk.support
  - flow_set: user
  - type: meya.zendesk.support.component.ticket.update
    integration: integration.zendesk.support
    comment: Verified (@ flow.phone == flow.user.phone )
    comment_public: false

  - (get_price)
  - flow_set:
      price_table:
        shoes: 40
        socks: 8
        sandals: 20
  - type: meya.zendesk.support.component.ticket.update
    integration: integration.zendesk.support
    comment: Price for (@ flow.groups.product ) $(@ flow.price_table[flow.groups.product]
      )
    comment_public: false
