triggers:
  - keyword: zendesk_support_user_search

steps:
  - say: What is the user's email?
  - type: email_address_input
    required: true
  - type: meya.zendesk.support.component.user.search
    integration: integration.zendesk.support
    query:
      - email:(@ flow.result )
  - say: Users found are (@ flow.result )
