triggers:
  - keyword: user_set

steps:
  - (start)
  - ask: start (@ user.__data__ )
    tiles:
      - title: Set
        buttons:
          - text: BFML
            action:
              jump: bfml_set
          - text: Python
            action:
              jump: py_set
              data:
                clear: false
                error: false
          - text: Python (error)
            action:
              jump: py_set
              data:
                clear: false
                error: true
      - title: Clear
        buttons:
          - text: BFML
            action:
              jump: bfml_clear
          - text: Python
            action:
              jump: py_set
              data:
                clear: true
                error: false
          - text: Python (error)
            action:
              jump: py_set
              data:
                clear: true
                error: true

  - (bfml_set)
  - user_set:
      user_data_1: []
      user_data_2: {}
      user_data_3: {key: !!null ''}
      user_data_4: {key1: x, key2: !!null ''}
      user_data_5:
        - {}
        - key1: x
          key2:
          key3: []
          key4:
            - 1
            - 
            - key5:
              key6: y
  - jump: end

  - (bfml_clear)
  - user_set:
      user_data_1:
      user_data_2:
      user_data_3:
      user_data_4:
      user_data_5:
  - jump: end

  - (py_set)
  - type: component.user.set
    clear: (@ flow["clear"] )
    error: (@ flow.error )
  - jump: end

  - (end)
  - say: end (@ user.__data__ )
    quick_replies:
      - user_set
  - end
