triggers:
  - keyword: name

steps:
  - say: Hey there...
  - continue_screen
  - ask: What's your name?
    composer:
      placeholder: For example, Dorinda
  - user_set: name
  - say: Nice to meet you, (@ user.name ) 🔥
