triggers:
  - keyword: name_form
steps:
  - say: Hey there...
  - ask_form: What's your name?
    label: Name
    autocomplete: name
    composer:
      visibility: hide
  - user_set: name
  - say: Nice to meet you, (@ user.name ) 🔥
