triggers:
  - keyword: text_multi

steps:
  - say: First message (1 of 5)...
  - delay: 1
  - say: Second message (2 of 5)...
  - delay: 1
  - say: Third message (3 of 5)...
  - delay: 1
  - say: Fourth message (4 of 5)...
  - delay: 1
  - say: Fifth message (5 of 5)...
