triggers:
  - keyword: regex_input

steps:
  - say: What's your postal code?
  - regex_input: >
      ^
      ([A-Za-z]\d[A-Za-z])
      [ -]?
      (?P<second_part>\d[A-Za-z]\d)
      $
    error_message: Invalid postal code, please try again.
  - say: 'Flow data: (@ flow )'
  - flow_set: postal_code
  - say: flow.postal_code = (@ flow.postal_code )
