triggers:
  - keyword: name_form

steps:
  - say: Hey there, what's your name?
  - type: text_input
    label: Name
    required: true
    composer:
      visibility: hide
  - user_set: name
  - say: Nice to meet you, (@ user.name ) 🔥
