triggers:
  - regex: \bfront.human\b

steps:
  - if: (@ user.name )
    then:
      jump: escalate
    else: next
  - ask: What's your name?
  - user_set: name
  - say: Nice to meet, you (@ user.name )! 👋

  - note: This note appears before agent escalation

  - (escalate)
  - say: One moment while I find someone to help...
  - type: meya.front.component.conversation.update
    integration: integration.front
    assignee_email:

  - note: This note appears after agent escalation
