id: front.agent.assign
triggers:
  - event_type: meya.front.event.agent.assign
steps:
  - status: Conversation assigned to an agent
---
id: front.agent.unassign
triggers:
  - event_type: meya.front.event.agent.unassign
steps:
  - status: Conversation unassigned
---
id: front.tag
triggers:
  - event_type: meya.front.event.tag.add
steps:
  - status: Tag (@ flow.event.data.payload.name ) added
---
id: front.untag
triggers:
  - event_type: meya.front.event.tag.remove
steps:
  - status: Tag (@ flow.event.data.payload.name ) removed
---
id: front.trash
triggers:
  - event_type: meya.front.event.conversation.trash
steps:
  - status: Conversation (@ flow.event.data.payload.conversation.id ) was deleted
---
id: front.reopen
triggers:
  - event_type: meya.front.event.conversation.reopen
steps:
  - status: Conversation (@ flow.event.data.payload.conversation.id ) was reopened
---
id: front.archive
triggers:
  - event_type: meya.front.event.conversation.archive
steps:
  - status: Conversation (@ flow.event.data.payload.conversation.id ) was archived
---
id: front.restore
triggers:
  - event_type: meya.front.event.conversation.restore
steps:
  - status: Conversation (@ flow.event.data.payload.conversation.id ) was restored
