triggers:
  - type: meya.twilio.voice.trigger.ringing
    direction: outbound-api

steps:
  - say: Hi (@ user.name). Give me a moment to get your order number.
  - delay: 2
  - say: I see that your order number is (@ user.order_number). How can I help you?

  - type: meya.twilio.voice.component.gather
    input: dtmf
    ask: Press 1 for order status, 2 to cancel your order or 3 to talk to an agent
  - flow_set: gather_decision

  - if: (@ flow.gather_decision | int == 1)
    then:
      jump: decision 1
    else: next

  - if: (@flow.gather_decision | int == 2)
    then:
      jump: decision 2
    else: next

  - say: Thanks. I'll transfer you to an agent now. One moment.
  - type: meya.twilio.voice.component.dial
    number: '+12267793766'
  - end

  - (decision 1)
  - say: Your order has shipped and will arrive shortly.
  - end

  - (decision 2)
  - say: Sorry to hear that. You're order is cancelled.
  - end
