triggers:
  - file
  - keyword: file
  - keyword: file_no_ask
    action:
      data:
        no_ask: true

steps:
  - file: https://upload.wikimedia.org/wikipedia/commons/b/b3/Wiki_markup_cheatsheet_EN.pdf
    name: cheatsheet.pdf
    icon: (@ config.icon.pdf_file )

  - file: https://www.w3.org/TR/PNG/iso_8859-1.txt
    name: iso.txt
    icon: (@ config.icon.txt_file )

  - file: https://httpbin.org/headers
    name: headers.json

  - if: (@ flow.get("no_ask") )
    then: end
    else: next

  - ask: What file do you have?
    expect: file
    composer:
      placeholder: Find a file
  - say: Thanks (@ flow )
