triggers:
  - file
  - keyword: file

steps:
  - url: https://upload.wikimedia.org/wikipedia/commons/b/b3/Wiki_markup_cheatsheet_EN.pdf
    filename: cheatsheet.pdf
    icon: (@ config.icon.pdf_file )

  - url: https://www.w3.org/TR/PNG/iso_8859-1.txt
    filename: iso.txt
    icon: (@ config.icon.txt_file )

  - url: https://httpbin.org/headers
    filename: headers.json

  - ask: What file do you have?
    expect: file
    composer:
      placeholder: Find a file
  - say: Thanks (@ flow )
