triggers:
  - keyword: _reply_to

steps:
  - type: meya.mailgun.component.send
    integration: integration.mailgun
    wait_for_response: true
    to:
      - name: Erik Kalviainen
        email: erik@meya.ai
    from:
      name: Adam Neumann
      email: bots@meya.ai
    subject: ✨ Testing reply-to
    text: This is the text body. 💪
    headers:
      Reply-To: adam@wework.com
  - say: Done. (@ flow.ok ) - (@ flow.status ) - (@ flow.result )
