triggers:
  - keyword: _mailgun
  - keyword: _mailgun2
    action:
      jump: send
      data:
        name: Erik Kalviainen
        email: erik@meya.ai
        subject: '[mailgun] Testing demo app'
        text: This is text.
        html: >
          This is <strong>HTML</strong>.<br/>
          <a href="https://meya.ai">Meya.ai</a>

steps:
  - say: Let's test sending an email using Mailgun.
  - say: What email to send to?
  - type: email_address_input
    required: true
  - flow_set: email
  - say: Name?
  - type: text_input
    required: true
  - flow_set: name
  - say: Subject?
  - type: text_input
    required: true
  - flow_set: subject
  - say: Text?
  - type: text_input
    required: true
  - flow_set: text
  - flow_set:
      html:
  - (send)
  - type: meya.mailgun.component.send
    integration: integration.mailgun
    wait_for_response: true
    to:
      - name: (@ flow.name )
        email: (@ flow.email )
    from:
      name: Meya Support
      email: support@meya.ai
    subject: (@ flow.subject )
    text: (@ flow.text )
    html: (@ flow.html )
  - if: (@ flow.ok )
    then: next
    else:
      jump: fail
  - say: Done. Check (@ flow.email ) for an email. (@ flow.result )
  - end
  - (fail)
  - say: Mailgun API failed. (@ flow.result )
