id: flow.freshchat.request_agent

triggers:
  - regex: freshchat

steps:
  - type: meya.csp.component.session.agent.request
    integration: integration.freshchat
    say: Transferring you to the next available agent.
    note: Here is a note for the agent.
    data:
      user:
        email: user12345@meya.ai
        phone: '+12261234444'
        properties:
          - name: orderId
            value: '44325'
          - name: memberId
            value: '11111'
        first_name: User12345
        last_name: Anon
      assign_to_agent: roeland@meya.ai
      assign_to_group: Success
---
id: flow.freshchat.chat_reopened

triggers:
  - event_type: meya.freshworks.freshchat.event.session.reopen

steps:
  - say: The chat with the agent has been reopend.
---
id: flow.freshchat.chat_resolved

triggers:
  - event_type: meya.freshworks.freshchat.event.session.resolve

steps:
  - say: The agent resolved the conversation.
---
id: flow.freshchat.chat_assigned

triggers:
  - event_type: meya.freshworks.freshchat.event.session.assign
    when: true

steps:
  - type: meya.text.component.say
    say: The agent assigned the chat to another agent. thread.mode = (@ thread.mode
      )
---
id: flow.freshchat.bot_take_over

triggers:
  - keyword: takeover
    when: true

steps:
  - type: meya.csp.component.session.agent.request
    say: Taking over the conversation from the agent.
    integration: integration.freshchat
    note: User asked me to take over.
    data:
      assign_to_agent: roeland+assistant@meya.ai
      assign_to_group: Bot
---
id: flow.freshchat.command.button

triggers:
  - agent_command: resolve
    when: (@ thread.mode is not none )

steps:
  - hero: Do you want to continue?
    description: 'Please pick an option:'
  - buttons:
      - text: Continue
        action:
          jump: continue
      - text: Resolve
        action:
          jump: resolve

  - (resolve)
  - type: meya.csp.component.session.end
    integration: integration.freshchat
  - end

  - (continue)
  - end
