triggers:
  - keyword: _split_name

steps:
  - say: Split name string...
  - say: What's your name?
  - type: text_input
    required: true
  - type: meya.util.text.component.split_name
    name: (@ flow.result )
  - say: first=(@ flow.result.first_name ) last=(@ flow.result.last_name )
