triggers:
  - keyword: Astronomy

steps:
  - image: https://media.giphy.com/media/3o7buijTqhjxjbEqjK/giphy.gif
    alt: BBC space GIF travelling through stars
    quick_replies:
      - text: Astronomy
        action:
          flow: flow.orb.page_header.astronomy
      - text: Cosmology
        action:
          flow: flow.orb.page_header.cosmology
      - text: Astrophysics
        action:
          flow: flow.orb.page_header.astrophysics
      - text: Astrobiology
        action:
          flow: flow.orb.page_header.astrobiology
