triggers:
  - keyword: 👩‍🚀

steps:
  - continue_screen
  - ask: 👽👽👽
    buttons:
      - text: 🐙
        action: next
      - text: 🛸
        action: next
      - text: 🖖
        action: next
  - say: 😄🚀⭐️
    quick_replies:
      - text: Astronomy
        action:
          flow: flow.orb.page_header.astronomy
      - text: Cosmology
        action:
          flow: flow.orb.page_header.cosmology
      - text: Astrophysics
        action:
          flow: flow.orb.page_header.astrophysics
      - text: Astrobiology
        action:
          flow: flow.orb.page_header.astrobiology
