triggers:
  - keyword: tile_links
    action:
      data:
        button_style: action
  - keyword: tile_links_radio
    action:
      data:
        button_style: radio
  - keyword: tile_links_text
    action:
      data:
        button_style: text

steps:
  - say: Tile links
  - tiles:
      - buttons:
          - text: Web
            url: https://example.org
          - text: Email
            url: mailto:support@meya.ai
          - text: Phone
            url: tel:+18889077680
    button_style: (@ flow.button_style )

