triggers:
  - keyword: tile_options

steps:
  - ask:
    button_style: radio
    layout: column
    tiles:
      - title: How many copies?
        buttons:
          - text: '1'
            result: 1
          - text: '2'
            result: 2
          - text: '3'
            result: 3
          - text: 4+
            result: 4
  - say: Flow result (@ flow.result )
