triggers:
  - keyword: tile_yes_no

steps:
  - ask:
    button_style: action
    layout: column
    tiles:
      - title: Do you want to continue?
        buttons:
          - text: Yes
            result: true
          - text: No
            result: false
  - say: Flow result (@ flow.result )
