triggers:
  - keyword: front_delete_contact_handle

steps:
  - ask: Contact id?
    quick_replies:
      - text: skip
        action:
          jump: ask_handle
  - flow_set: contact_id

  - (ask_handle)
  - ask: Handle?
  - flow_set: contact_handle

  - ask: Contact source?
    buttons:
      - text: custom
        result: custom
      - text: smooch
        result: smooch
      - text: email address
        result: email
      - text: phone
        result: phone
      - text: twitter
        result: twitter
      - text: facebook
        result: facebook
      - text: intercom
        result: intercom
  - flow_set: contact_source

  - ask: Force delete? If it's the last handle the contact will be deleted
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: force

  - type: meya.front.component.contact.handle.delete
    contact_id: (@ flow.get('contact_id') )
    handle: (@ flow.contact_handle )
    source: (@ flow.contact_source )
    force: (@ flow.force )
    integration: integration.front

  - if: (@ not flow.get('ok') )
    then: end
    else: next

  - (success_message)
  - say: Successfully deleted handle `(@ flow.contact_handle )` from the contact
