triggers:
  - keyword: zendesk_chat_session_start
  - keyword: zendesk_chat_session_start_2
    action:
      jump: transfer
      data:
        name: Test Visitor
        email: test@meya.ai
        phone: 123-456-7890

steps:
  - (name)
  - say: Name?
  - type: text_input
    required: true
    icon: (@ config.icon.person )
  - flow_set: name
  - (email)
  - say: Email?
  - type: email_address_input
    required: true
  - flow_set: email
  - (phone)
  - say: Phone?
  - type: text_input
    required: true
    icon: (@ config.icon.phone )
  - flow_set: phone

  - (transfer)
  - note: This is a note before chat start
  - open_chat
  - say: Start session -> (@ flow.name ) (@ flow.email ) (@ flow.phone )
  - type: meya.zendesk.chat.component.session.start
    integration: integration.zendesk.chat
    visitor_name: (@ flow.name )
    visitor_email: (@ flow.email )
    visitor_phone: (@ flow.phone )
    visitor_user_agent: (@ thread.page_open.user_agent )
    visitor_referrer: (@ thread.page_open.url )
    tags: [demo, meya]
    department: Support
  - note: This is a note after chat start
