triggers:
  - agent_command: training
    when: (@ thread.mode == "blue" )

steps:
  # Publish as the agent
  - event_user_id: (@ flow.event.data.user_id )
    scope: flow
  - say: Neo training
  - image: https://media.giphy.com/media/V2ojLo7PvhVug/giphy.gif
    alt: Neo gestures "come on"
