triggers:
  - keyword: _segment_track
  - keyword: _segment_track2
    action:
      jump: track
      data:
        event_name: foo

steps:
  - say: start segment track test...
  - say: event name?
  - type: text_input
    required: true
  - flow_set: event_name
  - (track)
  - track: custom.segment.event.(@ flow.event_name )
    data:
      foo: bar
      pi: 3.1415926535
    context:
      ip: 127.0.0.1
      country: canada
  - say: done.
