triggers:
  - keyword: email

steps:
  - (start)
  - type: email_address_input
    required: true
    icon: (@ config.icon.email_address )
    quick_replies:
      - text: Why do you need my email?
        action:
          jump: why
      - Where is your privacy statement?
    composer:
      visibility: collapse
      placeholder: Have a question?
    error_message: Not a valid email address, please try again.
  - if: (@ flow.result.startswith("test") )
    then:
      jump: test_email
    else: next

  - (valid_email)
  - say: Hi (@ flow.result )️ 👋
  - user_set: email
  - end:
      ok: true
      email: (@ flow.result )

  - (test_email)
  - say: 'Flow data: (@ flow )'
  - user_set:
      email_dict: (@ flow.result )
      email_confidence: (@ flow.confidence )
  - user_set: email
  - say: |
      user.email = (@ user.email )
      user.email_dict = (@ user.email_dict ),
      user.email_confidence = (@ user.email_confidence )
  - flow_set: email
  - flow_set:
      email_dict: (@ flow.result )
      email_retries: (@ flow.retry_count )
  - say: |
      flow.email = (@ flow.email )
      flow.email_dict = (@ flow.email_dict )
      flow.email_retries = (@ flow.email_retries )
  - end

  - (why)
  - say: We need your email address to send you important messages
  - buttons:
      - text: OK
        action:
          jump: start
      - text: Cancel
        action:
          end:
            ok: false

