triggers:
  - keyword: email_template

steps:
  - ask: Let's test sending a templated email
    quick_replies:
      - OK
  - say: What's your email?
  - type: email_address_input
    label: email
    required: true
  - user_set: email
  - say: What's your name?
  - type: text_input
    label: name
    required: true
  - user_set: name
  - say: What's your favorite color?
  - type: text_input
    icon: streamline-light/12-design/05-colors:painting/color-tubes.svg
    label: color
    required: true
  - flow_set: favorite_color
  - file_path: template/email/welcome.html
    template: true
  - type: meya.mailgun.component.send
    integration: integration.mailgun
    wait_for_response: true
    to:
      - email: (@ user.email )
    from:
      name: Meya
      email: no-reply@meya.ai
    subject: Welcome!
    html: (@ flow.result )
  - say: Email sent! ✉️
