triggers:
  - keyword: _twilio_lookup
  - keyword: _twilio_lookup2
    action:
      jump: lookup
      data:
        phone_number: (226) 808-4934

steps:
  - (input)
  - ask_form: What's your mobile phone number?
    label: Phone
    icon: phone
    placeholder: 'Mobile phone #'
  - flow_set: phone_number

  - (lookup)
  - type: meya.twilio.component.lookup
    integration: integration.twilio
    phone_number: (@ flow.phone_number )
  - if: (@ flow.ok )
    then:
      jump: valid
    else: next

  - say: ❌ Invalid phone number. Try again. (@ flow.status ) -  (@ flow.data )
  - delay: 2
  - jump: input

  - (valid)
  - flow_set: enriched_phone
  - say: >
      ✅ Valid phone number. status=(@ flow.status )
      Formatted: (@ flow.enriched_phone.national_format)
      Country:  (@ flow.enriched_phone.country_code)
    quick_replies:
      - text: Try again
        action:
          jump: input
  - end
