triggers:
  - regex: ^calend.*

steps:
  - (book)
  - calendly: (@ vault.calendly.event_link )
    integration: integration.calendly
    title: Book a demo date
    description: Click "Schedule time" below to setup a face-to-face meeting.
    button_style: text
    prefill:
      name: Tope Awotono
      email: erik+tope@meya.ai
    rows:
      -   - cell: Customer specialist
            value: Kaiser Sose
      -   - cell: Email
            value: kaiser@meya.ai
  - if: (@ flow.result )
    then: next
    else:
      jump: fail

  - (success)
  - say: >
      Meeting booked with Kaiser Sose
      @ (@ flow.result.start_time )
  - end

  - (fail)
  - say: Nothing booked. Try again?
    quick_replies:
      - text: Try again
        action:
          jump: book
  - end
