type: meya.bot.element
triggers: (@ config.triggers )
flows:
  - demo.flow.ask_email
  - demo.flow.ask_email_composer
  - demo.flow.ask_name
  - demo.flow.ask_name_form
  - demo.flow.ask_regex
  - demo.flow.button
  - demo.flow.calendly.webhooks
  - demo.flow.calendly.calendar
  - demo.flow.cat
  - demo.flow.catchall
  - demo.flow.chat
  - demo.flow.composer
  - demo.flow.control.branch
  - demo.flow.control.case
  - demo.flow.control.cond
  - demo.flow.control.factorial
  - demo.flow.control.if
  - demo.flow.control.if_even
  - demo.flow.control.loop
  - demo.flow.control.match
  - demo.flow.control.random
  - demo.flow.control.subflow
  - demo.flow.control.subflow_child
  - demo.flow.countdown
  - demo.flow.clearbit.enrich
  - demo.flow.flood
  - demo.flow.freshchat.request_agent
  - demo.flow.freshchat.chat_reopened
  - demo.flow.freshchat.chat_resolved
  - demo.flow.freshchat.chat_assigned
  - demo.flow.freshchat.bot_take_over
  - demo.flow.freshchat.command.button
  - demo.flow.data
  - demo.flow.delay
  - demo.flow.echo
  - demo.flow.error
  - demo.flow.file
  - demo.flow.header.astrobiology
  - demo.flow.header.astronomy
  - demo.flow.header.astrophysics
  - demo.flow.header.cosmology
  - demo.flow.header.faq
  - demo.flow.header.login
  - demo.flow.image
  - demo.flow.js
  - demo.flow.latency
  - demo.flow.live_agent.agent_disconnect
  - demo.flow.live_agent.agent_transfer
  - demo.flow.live_agent.chat_ended
  - demo.flow.live_agent.chat_established
  - demo.flow.live_agent.chat_request_failed
  - demo.flow.live_agent.chat_request_success
  - demo.flow.live_agent.command.matrix
  - demo.flow.live_agent.command.pill
  - demo.flow.live_agent.command.training
  - demo.flow.live_agent.end_session
  - demo.flow.live_agent.queue_update
  - demo.flow.live_agent.request_agent
  - demo.flow.mailgun.send
  - demo.flow.mailgun.reply_to
  - demo.flow.palindrome
  - demo.flow.quick_replies
  - demo.flow.random.hex
  - demo.flow.screen
  - demo.flow.segment.track
  - demo.flow.segment.identify
  - demo.flow.slack.send
  - demo.flow.string.split_name
  - demo.flow.thread_set
  - demo.flow.tile
  - demo.flow.time.availability
  - demo.flow.twilio.lookup
  - demo.flow.user_set
  - demo.flow.visits
