triggers:
  - keyword: page_buttons_mixed

steps:
  - page:
      - buttons:
          - Text
          - text: Value
            value: value_x
          - text: Result
            result: result_x
          - text: Data
            icon: (@ config.icon.sun )
            data:
              data_a: 1
              data_b: 2
          - text: Action
            action:
              jump: action
              data:
                action_x: x
          - text: URL
            url: https://www.example.org?q=x
    submit:
      text: Next
    extra_buttons:
      - text: Result
        icon: (@ config.icon.help )
        result: result_z
      - text: Action
        icon: (@ config.icon.moon )
        action:
          jump: action
          data:
            action_x: z
    composer:
      visibility: show
    quick_replies:
      - text: Action
        action:
          jump: action
          data:
            action_y: y
      - text: URL
        url: https://www.example.org?q=y

  - say: Next executed (@ flow )
    quick_replies:
      - page_buttons_mixed
  - end

  - (action)
  - say: Action executed (@ flow )
    quick_replies:
      - page_buttons_mixed
