triggers:
  - keyword: page_sensitive

steps:
  - thread_set:
      mode: prechat
  - page:
      - info: |
          # Sensitive data
      - buttons:
          - text: Cat
            default: (@ user.pet_type == "Cat" )
          - text: Dog
            default: (@ user.pet_type == "Dog" )
        label: Animal?
        required: true
      - checkbox: Stripes
        label: Fur?
        default: (@ user.pet_stripes )
      - regex_input: ^[A-Z].*$
        label: Name
        required: true
        default: (@ user.pet_name )
        error_message: Needs to start with a capital letter
    sensitive: true

  - say: Your input is (@ flow.result )
  - user_set:
      pet_type: (@ flow.result[0] | encrypt_sensitive )
      pet_stripes: (@ flow.result[1] | encrypt_sensitive )
      pet_name: (@ flow.result[2] | encrypt_sensitive )
  - thread_set:
      mode:
