triggers:
  - keyword: front_create_contact
    action:
      data:
        contact_source: custom

steps:
  - ask: Name?
  - flow_set: name

  - ask: Contact source?
    buttons:
      - text: custom
        result: custom
      - text: smooch
        result: smooch
      - text: email address
        result: email
      - text: phone
        result: phone
      - text: twitter
        result: twitter
      - text: facebook
        result: facebook
      - text: intercom
        result: intercom
    quick_replies:
      - text: skip
        action:
          jump: ask_external_handle
  - flow_set: contact_source

  - (ask_external_handle)
  - ask: External handle?
    quick_replies:
      - text: skip
        action:
          jump: link_contact
  - flow_set: handle

  - (link_contact)
  - ask: Link contact?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: link

  - type: meya.front.component.contact.create
    name: (@ flow.name )
    is_spammer: false
    handle: (@ flow.get('handle') )
    source: (@ flow.get('contact_source') )
    link: (@ flow.link )
    integration: integration.front

  - say: 'Successfully created contact - id: (@ flow.result.id )'
