triggers:
  - keyword: front_create_or_update_contact
    action:
      data:
        name: Test
        avatar_url: https://images.prismic.io/meya-website/c63a142a-a049-4da2-8c83-842325e31449_scifi-robot.png

steps:
  - ask: Contact name?
  - flow_set: name

  - ask: Contact handle?
    quick_replies:
      - text: skip
        action:
          jump: link_contact
  - flow_set: handle

  - (link_contact)
  - ask: Link contact?
    buttons:
      - text: Yes
        result: true
      - text: No
        result: false
  - flow_set: link

  - type: meya.front.component.contact.create_or_update
    name: (@ flow.get('name') )
    avatar_url: (@ flow.get('avatar_url') )
    handle: (@ flow.get('handle') )
    link: (@ flow.link )
    integration: integration.front

  - if: (flow.ok)
    then:
      jump: success
    else: next

  - say: Failed to create contact. Please check logs and try again later
  - end

  - (success)
  - say: 'Successfully created/updated contact - Result: (@ flow.result )'
  - user_set:
      front_contact_handle: (@ flow.result.handle )
      front_contact_id: (@ flow.result.id )
  - delay: 3
