triggers:
  - keyword: fb_messenger_tiles

steps:
  - typing: on
  - delay: 2
  - ask: Meya tiles
    tiles:
      - title: Tacos
        description: Description
        url: https://www.cookingclassy.com/instant-pot-slow-cooker-salsa-chicken-tacos/
        image:
          url: https://www.cookingclassy.com/wp-content/uploads/2017/06/salsa-chicken-tacos-2.jpg
        buttons:
          - text: Order your meal
            button_id: tacos
      - title: Ramen
        description: Description
        image:
          url: https://40aprons.com/wp-content/uploads/2016/01/bacon-ramen-6.jpg
        buttons:
          - text: Order your meal
            button_id: tacos

