triggers:
  - keyword: Astronomy

steps:
  - url: https://media.giphy.com/media/3o7buijTqhjxjbEqjK/giphy.gif
    alt: BBC space GIF travelling through stars
    quick_replies:
      - text: Astronomy
        action:
          flow: demo.flow.header.astronomy
      - text: Cosmology
        action:
          flow: demo.flow.header.cosmology
      - text: Astrophysics
        action:
          flow: demo.flow.header.astrophysics
      - text: Astrobiology
        action:
          flow: demo.flow.header.astrobiology
