triggers:
  - keyword: tile
  - keyword: example tile
    action:
      jump: build
      data:
        layout: row
        button_style: action
        tile_count: 3
        image: true
        title: true
        description: true
        cell_row_count: 2
        cell_count: 2
        link_button_count: 2
        button_count: 2

steps:
  # flow.layout
  - ask: Pick your layout
    tiles:
      - image:
          url: https://media.giphy.com/media/QaXziP9rBZW4RhGXA1/source.gif
        buttons:
          - text: Row
            result: row
      - image:
          url: https://media.giphy.com/media/YRnb9pXbRxtBu9hghT/source.gif
        buttons:
          - text: Column
            result: column
    composer:
      visibility: hide
  - flow_set: layout

  # flow.button_style
  - tiles:
      - description: Pick a button style
        buttons:
          - text: Action
            result: action
          - text: Text
            result: text
          - text: Radio
            result: radio
    button_style: radio
    layout: (@ flow.layout )
  - flow_set: button_style

  # flow.tile_count
  - ask: Pick a tile count
    tiles:
      - image:
          url: https://images.unsplash.com/photo-1458682625221-3a45f8a844c7?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&&w=1000
        buttons:
          - text: '1'
            result: 1
          - text: '2'
            result: 2
          - text: '3'
            result: 3
          - text: '5'
            result: 5
          - text: '10'
            result: 10
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    quick_replies:
      - What's a tile?
    composer:
      placeholder: Ask your tile question here
  - flow_set: tile_count

  # flow.image
  - ask: Pick title & description
    tiles:
      - image:
          url: https://images.unsplash.com/photo-1511151083847-62cedb3a5ea2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=80
        result: true
      - description: No images
        result: false
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      visibility: hide
  - flow_set: image

  # flow.title
  # flow.description
  - ask: Pick title & description
    tiles:
      - title: Title
        description: Description
        result: [true, true]
      - title: Title
        result: [true, false]
      - description: Description
        result: [false, true]
      - buttons:
          - text: Nothing
            result: [false, false]
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      visibility: hide
  - flow_set:
      title: (@ flow.result[0] )
      description: (@ flow.result[1] )

  # flow.cell_row_count
  # flow.cell_count
  - ask: Pick a cells layout
    tiles:
      - image:
          url: https://media.giphy.com/media/OKEYg2ISpaedy/giphy.gif
        buttons:
          - text: 0 rows, 0 cells
            result: [0, 0]
      - image:
          url: https://media.giphy.com/media/LLBA0xy763Fgk/200w_d.gif
        description: 1 row
        buttons:
          - text: 1 cell
            result: [1, 1]
          - text: 2 cell
            result: [1, 2]
          - text: 3 cell
            result: [1, 3]
      - image:
          url: https://media.giphy.com/media/finu0kgoalrvgYEPn7/200w_d.gif
        description: 2 rows
        buttons:
          - text: 1 cell
            result: [2, 1]
          - text: 2 cell
            result: [2, 2]
          - text: 3 cell
            result: [2, 3]
      - image:
          url: https://media.giphy.com/media/8qrrHSsrK9xpknGVNF/giphy.gif
        description: 3 rows
        buttons:
          - text: 1 cell
            result: [3, 1]
          - text: 2 cell
            result: [3, 2]
          - text: 3 cell
            result: [3, 3]
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      visibility: hide
  - flow_set:
      cell_row_count: (@ flow.result[0] )
      cell_count: (@ flow.result[1] )

  # flow.link_button_count
  - tiles:
      - image:
          url: https://media.giphy.com/media/13YwW2GIveXMcM/giphy-downsized.gif
        title: Pick a link button count
        buttons:
          - text: '0'
            result: 0
          - text: '1'
            result: 1
          - text: '2'
            result: 2
          - text: '3'
            result: 3
          - text: '5'
            result: 5
          - text: '10'
            result: 10
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      visibility: hide
  - flow_set: link_button_count

  # flow.button_count
  - tiles:
      - image:
          url: https://media.giphy.com/media/9DgiLVDnCmiWUzOasR/giphy.gif
        description: Pick a button count
        buttons:
          - text: '0'
            result: 0
          - text: '1'
            result: 1
          - text: '2'
            result: 2
          - text: '3'
            result: 3
          - text: '5'
            result: 5
          - text: '10'
            result: 10
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      visibility: hide
  - flow_set: button_count

  # flow.tiles
  - (build)
  - demo.component.build_tiles
  - flow_set: tiles

  # end
  - ask: FINAL CHOICE
    tiles: (@ flow.tiles)
    button_style: (@ flow.button_style)
    layout: (@ flow.layout )
    composer:
      placeholder: FINAL PLACEHOLDER
  - say: FINAL RESULT (@ flow.result ) 🔥
