# This workflow will install Python and Meya dependencies, runs tests and code formatting check
name: Meya build

on:
  repository_dispatch:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.custom_github_token }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Google Cloud dependencies
        if: github.ref == 'refs/heads/master'
        run: |
          wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-243.0.0-linux-x86_64.tar.gz -O /opt/google-cloud-sdk-243.0.0-linux-x86_64.tar.gz
          tar -C /opt -zxf /opt/google-cloud-sdk-243.0.0-linux-x86_64.tar.gz
          rm /opt/google-cloud-sdk-243.0.0-linux-x86_64.tar.gz
          echo '${{ secrets.google_auth_json }}' > /var/tmp/keyconfig.json
          /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /var/tmp/keyconfig.json --project "${{ secrets.google_project_id }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade \
            --extra-index-url https://meya:${{ secrets.auth_token }}@grid.meya.ai/registry/pypi \
            "pygit2>=1.1.1" \
            "meya-sdk>=2.0.0" \
            "meya-cli>=2.0.0"
      - name: Authenticate using Meya auth token
        run: |
          meya auth add --grid-url https://grid.meya.ai --auth-token ${{ secrets.auth_token }}
      - name: Connect to production app
        run: |
          meya connect --grid-url https://grid.meya.ai --app-id ${{ secrets.app_id }}
      - name: Check code syntax and formatting
        run: meya check
      - name: Run tests
        run: meya test
      - name: Deploy app
        if: github.ref == 'refs/heads/master'
        run: meya push --force --build-image
      - name: Deploy website
        if: github.ref == 'refs/heads/master'
        run: /opt/google-cloud-sdk/bin/gsutil -h 'Cache-Control:public, max-age=86400,
          s-maxage=10' cp public/index.html gs://meya-v2-demo
      - name: Push snapshot
        if: github.ref == 'refs/heads/master' && !startsWith(github.repository, 'meya-customers/')
        run: |
          git config user.email build@meya.ai
          git config user.name "Meya Build"
          git remote add snapshot https://github.com/$(echo $GITHUB_REPOSITORY | sed -e 's,^meya-ai,meya-customers,')
          git fetch --depth 1 snapshot master
          SNAPSHOT_COMMIT=$(git commit-tree -p snapshot/master $GITHUB_SHA^{tree} -m Snapshot)
          git push snapshot $SNAPSHOT_COMMIT:refs/heads/master
