# This workflow will install Python and Meya dependencies, runs tests and code formatting check
name: Meya build

on:
  repository_dispatch:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.custom_github_token }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade \
            --extra-index-url https://meya:${{ secrets.auth_token }}@grid.meya.ai/registry/pypi \
            "pygit2>=1.1.1" \
            "meya-sdk>=2.0.0" \
            "meya-cli>=2.0.0"
      - name: Authenticate using Meya auth token
        run: |
          meya auth add --grid-url https://grid.meya.ai --auth-token ${{ secrets.auth_token }}
      - name: Connect to production app
        run: |
          meya connect --grid-url https://grid.meya.ai --app-id ${{ secrets.app_id }}
      - name: Check code syntax and formatting
        run: meya check
      - name: Run tests
        run: meya test
      - name: Deploy app
        if: github.ref == 'refs/heads/master'
        run: meya push --force --build-image
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        if: github.ref == 'refs/heads/master'
        with:
          version: 321.0.0
          project_id: ${{ secrets.google_project_id }}
          service_account_key: ${{ secrets.google_auth_json_b64 }}
          export_default_credentials: true
      - name: Deploy website
        if: github.ref == 'refs/heads/master'
        run: gsutil -h 'Cache-Control:public, max-age=86400, s-maxage=10' cp public/index.html
          gs://meya-v2-demo
      - name: Push snapshot
        if: github.ref == 'refs/heads/master' && !startsWith(github.repository, 'meya-customers/')
        run: |
          git config user.email build@meya.ai
          git config user.name "Meya Build"
          git remote add snapshot https://github.com/$(echo $GITHUB_REPOSITORY | sed -e 's,^meya-ai,meya-customers,')
          git fetch --depth 1 snapshot master
          SNAPSHOT_COMMIT=$(git commit-tree -p snapshot/master $GITHUB_SHA^{tree} -m Snapshot)
          git push snapshot $SNAPSHOT_COMMIT:refs/heads/master
