triggers:
  - keyword: webv1_typing

steps:
  - say: >
      You can explicitly control typing by turning them on and off.
      For example let's turn typing on for 3 seconds, off for 1 second, then on for
      2 seconds...
  - typing: on
  - delay: 3
  - typing: off
  - delay: 1
  - typing: on
  - delay: 2
  - typing: off
  - say: Done!
